/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [SaperBase]    Script Date: 01.03.2019 19:00:13 ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'SaperBase')
BEGIN
	CREATE DATABASE [SaperBase]
END
GO

ALTER DATABASE [SaperBase] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SaperBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SaperBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SaperBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SaperBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SaperBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SaperBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [SaperBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SaperBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SaperBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SaperBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SaperBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SaperBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SaperBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SaperBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SaperBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SaperBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SaperBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SaperBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SaperBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SaperBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SaperBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SaperBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SaperBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SaperBase] SET RECOVERY FULL 
GO

ALTER DATABASE [SaperBase] SET  MULTI_USER 
GO

ALTER DATABASE [SaperBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SaperBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SaperBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SaperBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SaperBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SaperBase] SET QUERY_STORE = OFF
GO

USE [SaperBase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SaperBase] SET  READ_WRITE 
GO


